INSERT INTO `ramais`(`setor`, `ramal`, `localizacao`) VALUES
('Cozinha', '5004', 'Segundo andar, ala A'),
('Recepção', '5001', 'Térreo, ala B'),
('TI', '5002', 'Primeiro andar, ala C'),
('Financeiro', '5003', 'Segundo andar, ala B'),
('RH', '5005', 'Primeiro andar, ala A'),
('Marketing', '5006', 'Térreo, ala A'),
('Vendas', '5007', 'Terceiro andar, ala C'),
('Logística', '5008', 'Primeiro andar, ala D'),
('Suporte', '5009', 'Segundo andar, ala C'),
('Compras', '5010', 'Térreo, ala D'),
('Jurídico', '5011', 'Quarto andar, ala A'),
('Administração', '5012', 'Primeiro andar, ala E'),
('Pesquisa e Desenvolvimento', '5013', 'Segundo andar, ala D'),
('Atendimento ao Cliente', '5014', 'Térreo, ala C'),
('Contabilidade', '5015', 'Quarto andar, ala B'),
('Estoque', '5016', 'Terceiro andar, ala A'),
('Auditoria', '5017', 'Primeiro andar, ala B'),
('Treinamento', '5019', 'Primeiro andar, ala F'),
('Segurança', '5020', 'Térreo, ala F'),
('Desenvolvimento de Software', '5021', 'Quarto andar, ala D'),
('Diretoria', '5022', 'Quinto andar, ala A'),
('Planejamento Estratégico', '5023', 'Terceiro andar, ala B'),
('Gestão de Projetos', '5024', 'Primeiro andar, ala G'),
('Suprimentos', '5025', 'Térreo, ala E'),
('Engenharia', '5026', 'Quarto andar, ala C'),
('Comunicação Interna', '5027', 'Primeiro andar, ala H'),
('Serviços Gerais', '5028', 'Térreo, ala G'),
('Relações Públicas', '5029', 'Quarto andar, ala E'),
('Processos', '5030', 'Primeiro andar, ala I'),
('Tecnologia da Informação', '5031', 'Segundo andar, ala F'),
('Gestão de Pessoas', '5032', 'Primeiro andar, ala J'),
('Desenvolvimento de Produtos', '5033', 'Segundo andar, ala G'),
('Expansão', '5034', 'Terceiro andar, ala D'),
('Suporte Técnico', '5035', 'Quarto andar, ala F'),
('Marketing Digital', '5036', 'Primeiro andar, ala K'),
('Análise de Dados', '5037', 'Segundo andar, ala H'),
('Infraestrutura', '5038', 'Terceiro andar, ala E'),
('Logística Internacional', '5039', 'Quinto andar, ala B'),
('Arquitetura', '6001', 'Segundo andar, ala H'),
('Produção', '6002', 'Terceiro andar, ala F'),
('Recursos Humanos', '6003', 'Primeiro andar, ala L'),
('Pesquisa de Mercado', '6004', 'Quarto andar, ala G'),
('Logística Reversa', '6005', 'Térreo, ala K'),
('Planejamento de Eventos', '6006', 'Primeiro andar, ala M'),
('Gestão de Riscos', '6007', 'Terceiro andar, ala H'),
('Desenvolvimento Sustentável', '6008', 'Quinto andar, ala D'),
('Consultoria Externa', '6009', 'Segundo andar, ala I'),
('Design Gráfico', '6010', 'Primeiro andar, ala N'),
('Produção de Conteúdo', '6011', 'Térreo, ala L'),
('Inovação', '6012', 'Quarto andar, ala H'),
('Sistemas de Informação', '6013', 'Terceiro andar, ala I'),
('Gestão Financeira', '6014', 'Segundo andar, ala J'),
('Auditoria Interna', '6015', 'Quinto andar, ala F'),
('Compliance', '6016', 'Primeiro andar, ala O'),
('Comunicação Visual', '6017', 'Quarto andar, ala J'),
('Vendas Corporativas', '6018', 'Térreo, ala M'),
('Estratégia Comercial', '6019', 'Primeiro andar, ala P'),
('Segurança do Trabalho', '6020', 'Quarto andar, ala K'),
('Tecnologia de Produtos', '6021', 'Primeiro andar, ala Q'),
('Gestão de Qualidade', '6022', 'Terceiro andar, ala J'),
('Marketing Institucional', '6023', 'Quinto andar, ala G'),
('Suporte de TI', '6024', 'Primeiro andar, ala R'),
('Gestão de Inovação', '6025', 'Quarto andar, ala L'),
('Consultoria Jurídica', '6026', 'Térreo, ala N'),
('Produção Audiovisual', '6027', 'Segundo andar, ala K'),
('Marketing Estratégico', '6028', 'Primeiro andar, ala S'),
('Atendimento Técnico', '6029', 'Quarto andar, ala M'),
('Gestão de Logística', '6030', 'Segundo andar, ala L'),
('Serviços de Limpeza', '6031', 'Térreo, ala O'),
('Sistemas Operacionais', '6032', 'Quinto andar, ala H'),
('Estudos de Mercado', '6033', 'Terceiro andar, ala K'),
('Tecnologia Educacional', '6034', 'Primeiro andar, ala T'),
('Gestão de Redes', '6035', 'Segundo andar, ala M'),
('Desenvolvimento de Jogos', '6036', 'Térreo, ala P'),
('Design de Interiores', '6037', 'Primeiro andar, ala U'),
('Gestão de Contratos', '6038', 'Quarto andar, ala N'),
('Pesquisa Tecnológica', '6039', 'Terceiro andar, ala L'),
('Controle de Estoque', '6040', 'Segundo andar, ala N'),
('Serviços de Alimentação', '6041', 'Primeiro andar, ala V'),
('Operações Industriais', '6042', 'Quinto andar, ala I'),
('Gestão de Custos', '6043', 'Térreo, ala Q'),
('Engenharia de Processos', '6044', 'Quarto andar, ala O'),
('Desenvolvimento Digital', '6045', 'Primeiro andar, ala W'),
('Infraestrutura de Redes', '6046', 'Terceiro andar, ala M'),
('Desenvolvimento de Software Mobile', '6047', 'Quinto andar, ala J'),
('Gestão de Marketing Digital', '6048', 'Térreo, ala R'),
('Gestão de Projetos Comerciais', '6049', 'Primeiro andar, ala X'),
('Monitoramento de Dados', '6050', 'Quarto andar, ala P');